"""add ingestion ledger and ingestion_id FK - nullable is ok

Revision ID: 22967c0bdd71
Revises: 2a6c0d8034ab
Create Date: 2025-09-13 22:09:26.826748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22967c0bdd71'
down_revision: Union[str, Sequence[str], None] = '2a6c0d8034ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_ledger',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rows_ingested', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('event_id')
    )
    op.add_column('statement_of_reasons', sa.Column('ingestion_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'statement_of_reasons', 'ingestion_ledger', ['ingestion_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statement_of_reasons', type_='foreignkey')
    op.drop_column('statement_of_reasons', 'ingestion_id')
    op.drop_table('ingestion_ledger')
    # ### end Alembic commands ###
