"""create statement_of_reasons table

Revision ID: 2a6c0d8034ab
Revises: 
Create Date: 2025-09-13 20:46:32.477185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a6c0d8034ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_of_reasons',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('decision_visibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_visibility_other', sa.Text(), nullable=True),
    sa.Column('end_date_visibility_restriction', sa.Date(), nullable=True),
    sa.Column('decision_monetary', sa.Text(), nullable=True),
    sa.Column('decision_monetary_other', sa.Text(), nullable=True),
    sa.Column('end_date_monetary_restriction', sa.Date(), nullable=True),
    sa.Column('decision_provision', sa.Text(), nullable=True),
    sa.Column('end_date_service_restriction', sa.Date(), nullable=True),
    sa.Column('decision_account', sa.Text(), nullable=True),
    sa.Column('end_date_account_restriction', sa.Date(), nullable=True),
    sa.Column('account_type', sa.Text(), nullable=True),
    sa.Column('decision_ground', sa.Text(), nullable=True),
    sa.Column('decision_ground_reference_url', sa.Text(), nullable=True),
    sa.Column('illegal_content_legal_ground', sa.Text(), nullable=True),
    sa.Column('illegal_content_explanation', sa.Text(), nullable=True),
    sa.Column('incompatible_content_ground', sa.Text(), nullable=True),
    sa.Column('incompatible_content_explanation', sa.Text(), nullable=True),
    sa.Column('incompatible_content_illegal', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_addition', sa.Text(), nullable=True),
    sa.Column('category_specification', sa.Text(), nullable=True),
    sa.Column('category_specification_other', sa.Text(), nullable=True),
    sa.Column('content_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_type_other', sa.Text(), nullable=True),
    sa.Column('content_language', sa.Text(), nullable=True),
    sa.Column('content_date', sa.Date(), nullable=True),
    sa.Column('content_id_ean', sa.Text(), nullable=True),
    sa.Column('territorial_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('decision_facts', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_identity', sa.Text(), nullable=True),
    sa.Column('automated_detection', sa.Boolean(), nullable=True),
    sa.Column('automated_decision', sa.Text(), nullable=True),
    sa.Column('platform_name', sa.Text(), nullable=True),
    sa.Column('platform_uid', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_of_reasons')
    # ### end Alembic commands ###
